//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOLayerMedCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DocID { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public int RegionID { get; set; }
        public string Password { get; set; }
        public bool isActive { get; set; }
        public string TariffCode { get; set; }
        public bool isOnline { get; set; }
    
        public virtual Region Region { get; set; }
         
    }
}
