//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOLayerMedCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int scheduleID { get; set; }
        public int doctorID { get; set; }
        public Nullable<System.TimeSpan> fromtime { get; set; }
        public Nullable<System.TimeSpan> toTime { get; set; }
        public int threshold { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
